version = 0.1
[default.deploy.parameters]
stack_name = "polaroid-s3-cloudfront"
resolve_s3 = true
s3_prefix = "polaroid-cloudfront"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "BucketName=\"polaroid.proapplication.net\" DeploymentName=\"polaroid-hosting-bucket\""

